### ISSUE TITLE
After an initial install, an exception with the test

### ISSUE THREAD

**Issue by martinstreicher** [crashbreak/crashbreak#1]
```
Testing communication with server...
rake aborted!
NoMethodError: undefined method `gsub' for nil:NilClass
/Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/crashbreak-1.1.3/lib/crashbreak/dumpers/database_dumper.rb:48:in `inject_error_id'
/Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/crashbreak-1.1.3/lib/crashbreak/dumpers/database_dumper.rb:44:in `dump_command'
/Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/crashbreak-1.1.3/lib/crashbreak/dumpers/database_dumper.rb:24:in `dump_database'
/Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/crashbreak-1.1.3/lib/crashbreak/dumpers/database_dumper.rb:10:in `dump'
/Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/crashbreak-1.1.3/lib/crashbreak/exception_notifier.rb:28:in `block (2 levels) in dumpers_data'
/Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/crashbreak-1.1.3/lib/crashbreak/exception_notifier.rb:27:in `each'
/Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/crashbreak-1.1.3/lib/crashbreak/exception_notifier.rb:27:in `block in dumpers_data'
/Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/crashbreak-1.1.3/lib/crashbreak/exception_notifier.rb:26:in `tap'
/Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/crashbreak-1.1.3/lib/crashbreak/exception_notifier.rb:26:in `dumpers_data'
/Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/crashbreak-1.1.3/lib/crashbreak/exception_notifier.rb:16:in `dump_system_and_update_report'
/Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/crashbreak-1.1.3/lib/crashbreak/exception_notifier.rb:7:in `notify'
/Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/crashbreak-1.1.3/lib/tasks/crashbreak.rake:11:in `rescue in block (2 levels) in <top (required)>'
/Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/crashbreak-1.1.3/lib/tasks/crashbreak.rake:5:in `block (2 levels) in <top (required)>'
CrashbreakTestError: If you see this message everything works fine!
/Users/mss67/.rvm/gems/ruby-2.2.3@emerald/gems/crashbreak-1.1.3/lib/tasks/crashbreak.rake:6:in `block (2 levels) in <top (required)>'
Tasks: TOP => crashbreak:test
```

Is there a dependency on database dumper? Does it have to be installed or disabled?

**Comment by martinstreicher** [comment]
Removing the database dumper helped:

```
config.dumpers = [Crashbreak::RequestDumper.new] #Crashbreak::DatabaseDumper.new
```

However, I wonder if the default should include the dumper when additional configuration is required to actually use it. Perhaps it should be commented out as a section with instructions on how to complete the configuration and setup (S3, specifying the dump command to be used, etc.)

**Comment by mjaneczek** [comment]
@martinstreicher You have right! I already removed DatabaseDumper from initializer template. Will also update the readme file.

PS: Sorry for slow answer, I forgot to watch repo and didn't get any notification, sorry and thanks for your feedback!

**Comment by mjaneczek** [comment]
@martinstreicher I added section ["database dumper config"](https://github.com/crashbreak/crashbreak#databasedumper-config) to readme file. What do you think? Does it make a setup cleaner?
