### ISSUE TITLE
LoadError: cannot load such file (Capistrano)

### ISSUE THREAD

**Issue by inooid** [crashbreak/crashbreak#4]
When adding `require 'crashbreak/capistrano3'` to my `Capfile` I get an error.

Capistrano version: **capistrano (3.2.1)**

``` ruby
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

$ rails -v
Rails 4.2.4
```

``` ruby
$ cap production deploy:check --trace
cap aborted!
LoadError: cannot load such file -- crashbreak/deploys_repository
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/crashbreak-1.1.3/lib/tasks/crashbreak.cap:2:in `<top (required)>'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/crashbreak-1.1.3/lib/crashbreak/capistrano3.rb:1:in `load'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/crashbreak-1.1.3/lib/crashbreak/capistrano3.rb:1:in `<top (required)>'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/Users/my_macbook/projects/my_rails_project/Capfile:24:in `<top (required)>'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.2.1/lib/capistrano/application.rb:15:in `run'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.2.1/bin/cap:3:in `<top (required)>'
/Users/my_macbook/.rbenv/versions/2.2.3/bin/cap:23:in `load'
/Users/my_macbook/.rbenv/versions/2.2.3/bin/cap:23:in `<main>'
LoadError: cannot load such file -- crashbreak/capistrano3
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/my_macbook/projects/my_rails_project/Capfile:24:in `<top (required)>'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.2.1/lib/capistrano/application.rb:15:in `run'
/Users/my_macbook/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capistrano-3.2.1/bin/cap:3:in `<top (required)>'
/Users/my_macbook/.rbenv/versions/2.2.3/bin/cap:23:in `load'
/Users/my_macbook/.rbenv/versions/2.2.3/bin/cap:23:in `<main>'
```

**Comment by mjaneczek** [comment]
Hi @inooid, sorry for the slow answer (forgot to watch repo).

The bug should be fixed! Thanks for testing and please contact me with any problems! :smile:
